app:
  title: "Assistente de Análise de Crédito"
  host: "0.0.0.0"
  port: 8000

data:
  path: "./data"

rules:
  th_divida_receita: 1.0
  th_score_aprovar: 3.0
  th_score_revisar: 2.0

security:
  pii_minimization: true
  audit_log_path: "./logs/audit.csv"

monitoring:
  drift_baseline_window: 500
  psi_threshold: 0.2
